### PR TITLE
added buttons for missing ingredients

### PR DESCRIPTION
**Pull request by mostlybadfly**
just adding this for now for visibility,  I've converted the missing ingredients to buttons, they will add ingredient to bar, but need styling. trying to get them to display inline.

### CODE REVIEW

**Comment by mostlybadfly** [comment]
Got a btn-info colored button to show up for each missing ingredients, played around with CSS to make it green for add on hover, I will find the exact green used for "success". @tomekr do you happen to know how to change the text to display "add to bar" on hover? Not sure if it is something I can do in CSS, thoughts?

**Comment by tomekr** [comment]
Hmm, hover events aren't going to be very mobile friendly unfortunately (no concept of hover really).

I was thinking something along the lines of either a button/split-button dropdown (http://getbootstrap.com/components/#btn-dropdowns) or just making them small success buttons with a + icon (glyphicon glyphicon-plus-sign) to the left of of the text.

**Comment by mostlybadfly** [comment]
Just adding what I did so far.  I came across `url_for` and it seems to allow for the method and remote to trigger.  However, the layout with multiple missing ingredients still needs to be fixed, still working on that.

**Comment by mostlybadfly** [comment]
Made some additional changes. So now there is a glyphicon-plus next to the ingredient name.  I made it so that "btn-group" is being created within the missing_ingredient loop so now they line up.  You can notice those that on the rightmost "+" button there is an element off to the right. I need to figure out what that is.  There is now the question of js actions.  Removing tr when clicked to the next highest panel group.  Do I utilize "add_or_remove.js.erb" since it is hitting off of that controller or do I use a makeable_drinks specific js file?

**Pull request merged**
